set(WINDOWS TRUE)
set(CMAKE_SYSTEM_VERSION 10.0)
set(OCT_TARGET_PLATFORM "WINDOWS")
set(OCT_OUTPUT_DIR "win_x64")

set(CXX_FLAGS "/utf-8")
set(C_FLAGS "/utf-8")
set(EXE_LINKER_FLAGS "/INCREMENTAL")
set(SHARED_LINKER_FLAGS "INCREMENTAL")

set(CMAKE_CXX_FLAGS_DEBUG "${CXX_FLAGS} /ZI /Ob0 /Od /RTC1 /DDEBUG")
set(CMAKE_C_FLAGS_DEBUG "${C_FLAGS} /ZI /Ob0 /Od /RTC1 /DDEBUG")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/debug ${EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/debug /${SHARED_LINKER_FLAGS}")

set(CMAKE_CXX_FLAGS_RELWITHDEBUG "${CXX_FLAGS} /ZI /Ob0 /Od /RTC1 /DPROFILE /DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBUG "${C_FLAGS} /ZI /Ob0 /Od /RTC1 /DPROFILE /DNDEBUG")
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBUG "/debug /${EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBUG "/debug /${SHARED_LINKER_FLAGS}")

set(CMAKE_CXX_FLAGS_RELEASE "${CXX_FLAGS} /O2 /Ob2 /DRELEASE /DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE "${C_FLAGS} /O2 /Ob2 /DRELEASE /DNDEBUG")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/${EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/${SHARED_LINKER_FLAGS}")

add_compile_definitions(${OCT_TARGET_PLATFORM})